### ISSUE TITLE
Cannot find an overload for "UnicodeEncoding" and the argument count: "1" when processing .mof file

### ISSUE THREAD

**Issue by raks-patel** [qetza/vsts-replacetokens-task#17]
We're using DSC to generate .mof files.  However, we get an error when tries to do a token replacement on it.  Here's the output from part of the log.  It process .config files fine

	Agent:
	NewAgent-Build
	Start Time:
	7/23/2016 6:08 AM
	| Duration:
	00:00:03
	2016-07-23T05:08:01.3760081Z Executing the powershell script: C:\BuildAgent\tasks\replacetokens\1.3.0\replace-tokens.ps1
	 
	2016-07-23T05:08:02.5165502Z Replacing tokens in file 'C:\BuildAgent\_work\3122d4e92\New.App.CI\drop\__TargetMachine__.mof'...
	 
	2016-07-23T05:08:03.3604700Z ##[error]System.Management.Automation.MethodException: Cannot find an overload for "UnicodeEncoding" and the argument count: "1".
	 
	2016-07-23T05:08:03.3604700Z ##[error]   at System.Management.Automation.Adapter.GetBestMethodAndArguments(String methodName, MethodInformation[] methods, PSMethodInvocationConstraints invocationConstraints, Object[] arguments, Object[]& newArguments)
	 
	2016-07-23T05:08:03.3604700Z ##[error]   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
	 
	2016-07-23T05:08:03.3604700Z ##[error]   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)
	 
	2016-07-23T05:08:03.3916599Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: Unknown encoding 'Unicode'.

**Comment by qetza** [comment]
Hi @raks-patel,
Fix is on it's way.

**Comment by qetza** [comment]
Version 1.3.1 was released on the markeplace and contains the fix to encoding constructor parameters.

**Comment by raks-patel** [comment]
Hi @qetza,

That fix has worked.  Many thanks for the quick resolution
