### ISSUE TITLE
2017-08-14T18:43:19.8807344Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Name' because it is an empty string.

### ISSUE THREAD

**Issue by sprocter047** [qetza/vsts-replacetokens-task#44]
I am getting this error when replacing a token.  The token is getting replaced but this error comes up causing the build to be partially succeded.  Other builds are working fine with this step.  

2017-08-14T18:43:19.8807344Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Name' because it is an empty string.

90 
2017-08-14T18:43:19.8807344Z ##[error]   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)

91 
2017-08-14T18:43:19.8807344Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)

92 
2017-08-14T18:43:19.8817346Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)

93 
2017-08-14T18:43:19.8817346Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

94 
2017-08-14T18:43:19.8827334Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by qetza** [comment]
Hi @sprocter047,

Could you give me a little bit more details? What is the configuration of your task? Could you add the full debug log of the task (setting variable `debug` to `true`)?

Thanks
