### ISSUE TITLE
Error Installing on TFS 2017 on-prem

### ISSUE THREAD

**Issue by Akinnagbe** [qetza/vsts-replacetokens-task#65]
Please assist, was trying to install package to on premises TFS running vs 2017 Enterprise, got the error below
Found installed product - Visual Studio Enterprise 2017
4/19/2018 12:18:39 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

please assist.

**Comment by qetza** [comment]
Hi,

It seems you tried to install it by double-clicking it which is not how it is done to install TFS extensions. You can find the documentation here:
https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions?view=tfs-2018#install-extensions-for-disconnected-tfs
